import type { Metadata } from "next";
import { SITE_URL } from "@/lib/site";

export const SITE_NAME = "Ujjwal Jain";
export const DEFAULT_DESCRIPTION =
    "Full-stack engineer, backend-focused, building GenAI products end to end: APIs and data pipelines, LLM features with guardrails, and the interfaces around them. Every project links to its code and lists what it doesn't do yet.";

/** Generated by src/app/opengraph-image.tsx. Pages that set their own openGraph must reference it explicitly. */
const SOCIAL_IMAGE = "/opengraph-image";

export const PROFILE_LINKS = {
    github: "https://github.com/Ujjwaljain16",
    linkedin: "https://www.linkedin.com/in/ujjwal-jain-306b60323",
} as const;

interface PageMetadataInput {
    title: string;
    description: string;
    /** Path beginning with "/" (resolved against metadataBase). */
    path: string;
    type?: "website" | "article";
    /** Article-only fields. */
    publishedTime?: string;
    modifiedTime?: string;
    tags?: string[];
    /**
     * The route has its own opengraph-image file. Leave the image out here so Next
     * uses that file instead of the site-wide card.
     */
    ownImage?: boolean;
}

/**
 * Per-route metadata. Next replaces (does not merge) `openGraph` and `twitter`
 * from the layout, so each page must supply the complete objects.
 */
export function pageMetadata({ title, description, path, type = "website", publishedTime, modifiedTime, tags, ownImage = false }: PageMetadataInput): Metadata {
    const fullTitle = `${title} | ${SITE_NAME}`;
    return {
        title,
        description,
        alternates: { canonical: path },
        openGraph: {
            type,
            url: path,
            siteName: SITE_NAME,
            locale: "en_US",
            title: fullTitle,
            description,
            ...(ownImage ? {} : { images: [{ url: SOCIAL_IMAGE, width: 1200, height: 630, alt: "Ujjwal Jain: full-stack engineer, backend and GenAI" }] }),
            ...(type === "article"
                ? { publishedTime, modifiedTime, authors: [SITE_NAME], tags }
                : {}),
        },
        twitter: { card: "summary_large_image", title: fullTitle, description, ...(ownImage ? {} : { images: [SOCIAL_IMAGE] }) },
    };
}

/** Serialise JSON-LD for a <script> tag; `<` is escaped so content can't close the tag. */
export function jsonLd(data: Record<string, unknown>): string {
    return JSON.stringify(data).replace(/</g, "\\u003c");
}

export function personJsonLd(): Record<string, unknown> {
    return {
        "@context": "https://schema.org",
        "@type": "Person",
        name: SITE_NAME,
        jobTitle: "Full-stack engineer",
        url: SITE_URL,
        description: DEFAULT_DESCRIPTION,
        sameAs: [PROFILE_LINKS.github, PROFILE_LINKS.linkedin],
    };
}

export function articleJsonLd(post: {
    title: string;
    excerpt: string;
    slug: string;
    published: string;
    updated?: string;
    tags: string[];
}): Record<string, unknown> {
    const url = `${SITE_URL}/blogs/${post.slug}`;
    return {
        "@context": "https://schema.org",
        "@type": "Article",
        headline: post.title,
        description: post.excerpt,
        url,
        mainEntityOfPage: url,
        datePublished: post.published,
        dateModified: post.updated ?? post.published,
        keywords: post.tags.join(", "),
        author: { "@type": "Person", name: SITE_NAME, url: SITE_URL },
    };
}
